<?php require_once(__DIR__ . '/../config.php'); ?>
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-type" content="text/html; charset=UTF-8">
		<meta http-equiv="Content-Language" content="en-us">
		
		<title>Heblo</title>
		
		<meta name="keywords" content="mundo virtual, mundo online, avatar, mmo, mmop, mmorpg, jogo grátis, metaverso, chat 3d , 3d, bate-papo, 3-d" />
		<meta name="description" content="O Heblo é um jogo de última geração para jogar online, sem baixar nem instalar nada, completamente em 3D" />
		<meta name="copyright" content="Copyright 2020. Todos os Direitos Reservados" />
		
		<link type="text/css" href="<?php echo SHARED_CSS; ?>reset.css" rel="stylesheet" media="screen" />
		<link type="text/css" href="<?php echo SHARED_CSS; ?>common.css" rel="stylesheet" media="screen" />
		<link type="text/css" href="<?php echo SHARED_CSS; ?>jquery.fancybox.2.1.4.custom.css" rel="stylesheet" media="screen" />
		<link type="text/css" href="<?php echo WEBSITE_CSS; ?>game.css" rel="stylesheet" media="screen" />
		
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
		<script type="text/javascript" src="<?php echo SHARED_JS; ?>lib_api.js"></script>
		<script type="text/javascript" src="<?php echo WEBSITE_JS; ?>smallworlds.js"></script>
		<script type="text/javascript" src="<?php echo SHARED_JS; ?>swfobject.js"></script>
		<script type="text/javascript" src="<?php echo SHARED_JS; ?>jquery.fancybox.2.1.4.js"></script>
		<script type="text/javascript" src="<?php echo SHARED_JS; ?>facebook.js"></script>
		<script type="text/javascript" src="<?php echo WEBSITE_JS; ?>game.js"></script>
		
		<script type="text/javascript">
			$.sw.init({url: '<?php echo GATEWAY_URI; ?>', surl: '<?php echo GATEWAY_URI; ?>'});
		</script>
	</head>
	
	<body>
		<div id="mainContainer">
			<script type="text/javascript">
				var config = `<?php echo include_once(__DIR__ . "/config.php"); ?>`;
				var flashvars = { config: config };

				var params = { menu: 'false', allowScriptAccess: 'always', allowFullScreenInteractive: 'true', bgcolor: '#e1e1e1', wmode: 'window' };
				var attributes = { id: 'Main', name: 'Main' };
				swfobject.embedSWF("<?php echo CONTENT_CONTENT; ?>webassets/main_preloader.swf", "mainSwf", "100%", "100%", "10.0.0", "<?php echo SHARED_SWF; ?>expressInstall.swf", flashvars, params, attributes);
			</script>
			
			<div id="swfContainer" style="width: 100%; height: 100%;">
				<div id="mainSwf"><strong>O Heblo necessita do Adobe Flash Player para jogar. O Flash Player pode ser baixado <a href="http://get.adobe.com/br/flashplayer/" target="_blank">aqui</a>.</strong></div>
			</div>
			
			<link rel="stylesheet" href="<?php echo WEBSITE_CSS; ?>bootstrap.css">
			<link rel="stylesheet" href="<?php echo WEBSITE_CSS; ?>youtube.css">
			
			<script type="text/javascript" src="<?php echo WEBSITE_JS; ?>youtube.js"></script>
			<script type="text/javascript" src="<?php echo WEBSITE_JS; ?>vendor/bootstrap.js"></script> 
			<script type="text/javascript">
				function setupYtWidget(widgetId) {
					// Set localisation for some text that is generated by javascript.
					youtubeLocale.playlist = 'Lista de reprodução de';
					youtubeLocale.removeFromPlaylist = 'Remover o video da lista de reprodução';
					youtubeLocale.addVideoToPlaylist = 'Add vídeo à Playlist';
					
					youtubeLocale.contentPath = '<?php echo WEBSITE_IMG; ?>youtube/';
					
					// Setup the widget html and js player itself.
					$("body").append('<div class="ytWidget" style="display:none; background-color:#000000; background-image: url(\'<?php echo SHARED_IMG; ?>youtube/background.png\'); color:#ffffff; position:absolute; top:0px; left:0px; width:660px; height:490px; margin:8px;">		<div style="position:relative; width:100%; height:100%">			<div id="ytNavBar" style="font-size:80%; padding-top:5px; padding-right:20px;">			<div id="navVideo" class="ytNavButton" style="display:none;" onclick="toggleVideo();">Video</div>			<div id="navSearch" class="ytNavButton" onclick="toggleSearch();">Procurar</div>			<div id="navPlaylist" class="ytNavButton">Lista de reprodução de</div>			<div style="clear:both;"></div>		</div>					<div id="ytContent" style="width:640px; height:460px;">			<!-- Current playlist. -->			<div id="ytPlaylist" style="position:relative; width:100%; height:420px; display:block; padding-left:10px; padding-top:17px;">				<div id="playlistHeader" style="width:100%; text-align:center;">					Selecione o video para reproduzir				</div>								<div id="youtubeCarousel" class="carousel slide">					<div class="carousel-inner" style="margin-top: 50px;"></div>					<a class="carousel-control left" href="#youtubeCarousel" data-slide="prev" style="line-height:28px; left:30px; display:inline;">&lsaquo;</a>					<a class="carousel-control right" href="#youtubeCarousel" data-slide="next" style="line-height:28px; right:30px; display:inline;">&rsaquo;</a>				</div>											<div id="pageCounter" style="text-align:center; padding-bottom:20px;">					Video <span id="currentVideo"></span> of <span id="totalVideos"></span>				</div>								<div id="playlistEmpty" style="display:none; height:100%; padding:30px; text-align:center; padding-top:150px;">					Para iniciar a reprodução dos videos, procure videos em "Pesquisar" e selecione para sua lista				</div>								<div id="savePlaylist" style="position:absolute; bottom:15px; right:30px; color:#ffffff; cursor:pointer; font-size:80%; font-weight:bold;" onclick="savePlaylist();">					<u>Salvar lista de reprodução como padrão</u>				</div>			</div>						<!-- Search for a video on youtube. -->			<div id="ytSearch" style="width:100%; height:420px; position:relative; display:none;">				<div style="padding-top:15px; padding-left:40px; padding-right:40px;">					<input id="ytSearchText" placeholder="Insira sua pesquisa no YouTube" type="text" style="width:40%; padding:5px; height:14px; line-height:16px; margin-bottom:0px; font-size:12px;" onkeypress="return onSearchTextEnter(event);" />&nbsp;<input id="ytSearchBtn" type="button" value="IR" onclick="searchYoutube();" />					<span id="ytSearchMessage" style="color:#FFFFFF; display:none;"></span>					<div id="ytSearchError" style="color:#DD0000; display:none;"></div>				</div>								<!-- Search results. -->				<div id="ytSearchResults" style="padding-left:40px;"></div>								<div id="ytSearchResultsPaging" style="position:absolute; bottom:0px; right:20px; display:none; font-size:80%;">					Página <span id="searchPageCurr">1</span> de 4					&nbsp;&nbsp;&nbsp;&nbsp; 					<input type="button" id="previousSearchPage" class="youtubeBtn leftArrowBtn" disabled onclick="previousSearchPage();" /> 					&nbsp;&nbsp;&nbsp;					<input type="button" id="nextSearchPage" class="youtubeBtn rightArrowBtn" onclick="nextSearchPage();" />				</div>			</div>						<!-- Watch a video. -->			<div id="ytVideo" style="width:100%; height:420px; display:none; padding-left:30px; padding-top:2px;">					<div id="ytPlayer" style="width:600px; height:420px;"></div>				<div id="ytPlayback" style="height:32px; padding-top:5px; position:relative; text-align:center;">					<div style="position:absolute; bottom:8px; right:45px;">						<input type="button" class="youtubeBtn leftArrowBtn" title="Reproduzir o video anterior da lista" onclick="playPreviousVideo();" /> 						&nbsp;						<input type="button" class="youtubeBtn rightArrowBtn" title="Reproduzir o próximo vídeo da lista" onclick="playNextVideo();" />					</div>				</div>			</div>		</div>			<img style="position:absolute; bottom:15px; left:310px" src="<?php echo WEBSITE_IMG; ?>youtube/youtubecolor.png" />	</div></div>');
					$("body").children().last().attr('id', 'ytWidget_' + widgetId);
					
					var widget =$("#ytWidget_" + widgetId); 
					widget.find("#ytPlayer").attr('id', 'ytPlayer_' + widgetId);
					widget.data("widgetid", widgetId);
					loadYTApi();
					createYtPlayer(widgetId);
					
					// Set click handlers on nav buttons.
					widget.find("#navPlaylist").click(function(e){
						togglePlaylist(widgetId);
					});
					widget.find("#navSearch").click(function(e){
						toggleSearch(widgetId);
					});
					widget.find("#navVideo").click(function(e){
						toggleVideo(widgetId);
					});
					
					// PT needs a slightly bigger playlist button.
					if ('pt_BR' == 'pt_BR') {
						$("#navPlaylist").css("width", "150px");
					}
					
					// Fix the carousel arrows so they work correctly when multiple widgets are in the space.
					var carousel = widget.find("#youtubeCarousel");
					
					carousel.attr('id', 'youtubeCarousel_' + widgetId);
					carousel.find(".left").attr('href', '#youtubeCarousel_' + widgetId);
					carousel.find(".right").attr('href', '#youtubeCarousel_' + widgetId);
				}
			</script>
		</div>
		
		<div id="snapshotContainer">
			<script type="text/javascript">
				var flashvars = {};
				var params = { menu: 'false', allowScriptAccess: 'always', bgcolor: '#e1e1e1', wmode: 'opaque' };
				var attributes = { id: 'Snapshot', name: 'Snapshot' };
				swfobject.embedSWF("<?php echo CONTENT_CONTENT; ?>webassets/snapshot.swf", "snapshotSwf", "100%", "100%", "10.0.0", "<?php echo SHARED_SWF; ?>expressInstall.swf", flashvars, params, attributes);
			</script>
			
			<div id="snapshotSwf"></div>
		</div>
	</body>
</html>